name: pinterest_2022
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.0
  dio: ^4.0.4
  logger: ^1.1.0
  lottie: ^1.2.2
  image_picker: ^0.8.4+10
  image_downloader: ^0.31.0
  fluttertoast: ^8.0.9
  internet_connection_checker: ^0.0.1+3
  connectivity_plus: ^2.2.1
  retrofit: ^3.0.1+1
  json_annotation: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.4
  build_runner: ^2.1.7

flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/lottie/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

